grammar com.denschu.xtext.whitespace.MyDsl
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
generate myDsl "http://www.denschu.com/xtext/whitespace/MyDsl"

Test:
	TAB keyword=Keyword (TAB arg+=Argument)* EOL;

Keyword:
	keyword=String;

Argument:
	arg=String;

String returns ecore::EString:
	(ID|WS|OTHER)*;
	
terminal WS: ' ';
terminal ID: ('a'..'z')+;
terminal TAB: (WS WS | '\t')+;
terminal EOL: ('\r'? '\n')+;
terminal OTHER: .;