/*
 * generated by Xtext
 */
package com.denschu.xtext.whitespace;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends com.denschu.xtext.whitespace.AbstractMyDslRuntimeModule {

}
