grammar com.denschu.xtext.whitespace.MyDsl
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
generate myDsl "http://www.denschu.com/xtext/whitespace/MyDsl"

Test:
	TAB keyword=Keyword (TAB arg+=Argument)* EOL;

Keyword hidden() : ID (" " ID)*;

Argument hidden() : ID (" " ID)*;
	
terminal fragment WS: ('  ') (' ')*;
terminal ID: ('a'..'z')+;
terminal TAB: (WS | '\t')+;
terminal EOL: ('\r'? '\n')+;