grammar com.denschu.xtext.whitespace.MyDsl
import "http://www.eclipse.org/emf/2002/Ecore" as ecore
generate myDsl "http://www.denschu.com/xtext/whitespace/MyDsl"

Test:
	//name=ID EOL
	TAB keyword=Keyword (TAB INDENT arg+=Argument)* DEDENT EOL;

Keyword:
	keyword=ID;

Argument:
	arg=ID;

terminal fragment WS: ' ';
terminal ID: (('a'..'z') WS?)+;
terminal TAB: (WS | '\t')+;
terminal EOL: ('\r'? '\n')+;
terminal INDENT : '{';
terminal DEDENT : '}';