/*
* generated by Xtext
*/
package com.denschu.xtext.whitespace.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MyDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
