/*
* generated by Xtext
*/
package com.denschu.xtext.whitespace.ui.contentassist;

import com.denschu.xtext.whitespace.ui.contentassist.AbstractMyDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {

}
